### ISSUE TITLE
请教下safecopy的疑惑

### ISSUE THREAD

**Issue by heyuanjie87** [Jimx-/lyos#1]
要是驱动进程在执行copy过程中app进程被kill了咋办

**Comment by Jimx-** [comment]
之前的处理确实有问题，因为在 verify_endpt 里面只判断了进程号是否在范围里面，没有检查进程是否已经退出。加上检查之后应该没问题了。safecopy 调用 _vir_copy 的时候会调用 endpt_proc -> verify_endpt，如果进程已经退出或被 kill 的话会返回ESRCH给驱动进程，驱动进程再把错误返回给调用进程（比如 vfs）就可以了
